[versions]
agp = "8.8.0"
playServicesWearable = "19.0.0"
#noinspection GradleDependency
appcompat = "1.6.1"
#noinspection GradleDependency
material = "1.10.0"
#noinspection GradleDependency
activity = "1.8.0"
#noinspection GradleDependency
constraintlayout = "2.1.4"

[libraries]
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

